import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';
import { createClient } from 'npm:@supabase/supabase-js@2';
import { sendEmail } from '../_shared/gmail.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const authHeader = req.headers.get('Authorization') || '';
    const jwt = authHeader.replace('Bearer ', '');
    if (!jwt) return json({ error: 'Unauthorized' }, 401);

    const admin = createClient(SUPABASE_URL, SERVICE_KEY);
    const { data: userRes } = await admin.auth.getUser(jwt);
    const caller = userRes?.user;
    if (!caller) return json({ error: 'Unauthorized' }, 401);

    // Verify admin
    const { data: roles } = await admin
      .from('user_roles').select('role').eq('user_id', caller.id);
    const isAdmin = (roles || []).some((r: any) => r.role === 'admin');
    if (!isAdmin) return json({ error: 'Admin only' }, 403);

    const body = await req.json().catch(() => ({}));
    const email = String(body.email || '').trim().toLowerCase();
    const role = ['user', 'support', 'admin'].includes(body.role) ? body.role : 'user';
    const note = body.note ? String(body.note).slice(0, 500) : null;
    const appOrigin = String(body.origin || '').replace(/\/+$/, '');

    if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
      return json({ error: 'Valid email required' }, 400);
    }

    // Create the invitation (token auto-generated by DB default)
    const { data: inv, error: insErr } = await admin
      .from('invitations')
      .insert({ email, role, note, invited_by: caller.id })
      .select('*')
      .single();
    if (insErr) return json({ error: insErr.message }, 400);

    const link = `${appOrigin || 'https://privateintitute.lovable.app'}/auth?invite=${inv.token}&email=${encodeURIComponent(email)}`;

    const html = `
      <div style="font-family:'Inter',Arial,sans-serif;background:#f5f6fb;padding:32px;">
        <div style="max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 6px 24px rgba(20,30,60,0.08);">
          <div style="background:linear-gradient(135deg,#0b1f4d,#c8102e);padding:28px;text-align:center;color:#fff;">
            <div style="font-size:11px;letter-spacing:.35em;text-transform:uppercase;opacity:.85;">Wealth · Trust · Legacy</div>
            <h1 style="margin:8px 0 0;font-family:'Playfair Display',Georgia,serif;font-size:26px;">BoA <em style="color:#f7d774;">private</em> institute</h1>
          </div>
          <div style="padding:32px;color:#1e2540;">
            <h2 style="margin:0 0 12px;font-size:20px;">You've been invited</h2>
            <p style="margin:0 0 16px;line-height:1.55;">
              A private banking account has been reserved for <strong>${email}</strong>.
              Access to the portal is invite-only. Use the secure link below to create your account.
              This invitation expires in <strong>14 days</strong>.
            </p>
            ${note ? `<p style="margin:0 0 16px;padding:12px 14px;background:#f5f6fb;border-left:3px solid #c8102e;border-radius:6px;color:#4a5170;">${note}</p>` : ''}
            <div style="text-align:center;margin:28px 0;">
              <a href="${link}" style="display:inline-block;background:#0b1f4d;color:#fff;padding:14px 28px;border-radius:10px;text-decoration:none;font-weight:600;letter-spacing:.02em;">Accept Invitation</a>
            </div>
            <p style="font-size:12px;color:#7a809a;word-break:break-all;">Or open this link:<br/>${link}</p>
            <hr style="border:none;border-top:1px solid #eceef5;margin:24px 0;" />
            <p style="font-size:11px;color:#9199b2;line-height:1.5;">
              Role assigned: <strong>${role}</strong> · If you weren't expecting this email you can safely ignore it.
            </p>
          </div>
        </div>
      </div>`;

    try {
      await sendEmail(email, 'Your BoA private institute invitation', html);
    } catch (e) {
      // Email failed but invitation exists — return link so admin can share manually
      return json({ ok: true, invitation: inv, link, email_sent: false, email_error: String(e) });
    }

    return json({ ok: true, invitation: inv, link, email_sent: true });
  } catch (e: any) {
    return json({ error: e?.message || 'Unknown error' }, 500);
  }
});

function json(data: any, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
