// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-accounts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "Return the signed-in user's bank accounts with balances (account numbers redacted to last 4).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client(ctx).from("accounts").select("id,account_type,account_name,account_number,balance,available_balance,credit_limit,is_active").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const redacted = (data ?? []).map((a) => ({
      ...a,
      account_number: a.account_number ? `\u2022\u2022\u2022\u2022${String(a.account_number).slice(-4)}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(redacted, null, 2) }],
      structuredContent: { accounts: redacted }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List recent transactions",
  description: "Return the signed-in user's most recent transactions across all accounts.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many transactions to return (max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client2(ctx);
    const accounts = await sb.from("accounts").select("id").eq("user_id", ctx.getUserId());
    if (accounts.error) return { content: [{ type: "text", text: accounts.error.message }], isError: true };
    const ids = (accounts.data ?? []).map((a) => a.id);
    if (!ids.length) {
      return { content: [{ type: "text", text: "No accounts found." }], structuredContent: { transactions: [] } };
    }
    const { data, error } = await sb.from("transactions").select("id,account_id,transaction_type,amount,balance_after,description,category,status,created_at").in("account_id", ids).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payees.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payees_default = defineTool3({
  name: "list_payees",
  title: "List bill-pay payees",
  description: "Return the signed-in user's saved bill-pay payees (account numbers redacted).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client3(ctx).from("payees").select("id,payee_name,payee_type,account_number,is_active").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const redacted = (data ?? []).map((p) => ({
      ...p,
      account_number: p.account_number ? `\u2022\u2022\u2022\u2022${String(p.account_number).slice(-4)}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(redacted, null, 2) }],
      structuredContent: { payees: redacted }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fvrzpuxkehukgfjhjehh";
var mcp_default = defineMcp({
  name: "boa-private-institute-mcp",
  title: "BoA private institute",
  version: "0.1.0",
  instructions: "Read-only banking tools for the signed-in BoA private institute user. Use `list_accounts` for balances, `list_transactions` for recent activity, and `list_payees` for saved bill-pay recipients.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_accounts_default, list_transactions_default, list_payees_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
